spring:
  application:
    name: map-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
  mongodb:
    uri: ${SPRING_MONGODB_URI:mongodb://mongodb:27017/supercenter_map_db}
  cloud:
    config:
      fail-fast: false
