server:
  port: ${MAP_SERVICE_PORT:8083}

spring:
  mongodb:
    uri: ${MAP_MONGO_URI:mongodb://mongodb:27017/supercenter_map_db}

app:
  security:
    jwt:
      secret: ${JWT_SECRET:change-me-please-change-me-please-change-me-please-change-me}
